AllCops:
  Exclude:
    - 'berks-cookbooks/**/*'
    - '.kitchen/*'
    - 'Thorfile'
    - 'Berksfile'
    - 'Vagrantfile'
    - 'Gemfile'
    - 'Rakefile'

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 60
  CountComments: false
  Enabled: true

Style/Encoding:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/BracesAroundHashParameters:
  EnforcedStyle: false

Style/EmptyLiteral:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

Documentation:
  Enabled: false
